# Generated by Django 6.0.2 on 2026-02-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_companion', '0036_alter_transaction_time_of_transaction'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user'], name='financial_c_user_id_83906e_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', 'name'], name='financial_c_user_id_6906cb_idx'),
        ),
        migrations.AddIndex(
            model_name='accounttarget',
            index=models.Index(fields=['account'], name='financial_c_account_057e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user'], name='financial_c_user_id_a3b31c_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'name'], name='financial_c_user_id_d88953_idx'),
        ),
        migrations.AddIndex(
            model_name='categorytarget',
            index=models.Index(fields=['category'], name='financial_c_categor_b26294_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['sender_account'], name='financial_c_sender__ba1f0d_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['receiver_account'], name='financial_c_receive_da320a_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['start_date'], name='financial_c_start_d_d07a78_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['end_date'], name='financial_c_end_dat_8ba247_idx'),
        ),
        migrations.AddIndex(
            model_name='usertarget',
            index=models.Index(fields=['user'], name='financial_c_user_id_70fead_idx'),
        ),
    ]
