# Generated by Django 6.0.2 on 2026-02-17 19:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_companion', '0035_remove_recurringtransaction_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transaction',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
